version: "3"

services:
  postgesql:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - ./.docker/postgres:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=godb
      - PGDATA=/tmp
    networks: 
      - server_network

  clean_architecture:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - postgesql
    networks:
      - server_network

networks:
  server_network:
    driver: bridge
